DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS good_order;
DROP TABLE IF EXISTS good_category;
DROP TABLE IF EXISTS goods;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS status;

CREATE TABLE users (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255),
	second_name varchar(255),
	email varchar(255),
	is_admin boolean
);

CREATE TABLE goods (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255),
	cost int NOT NULL,
	count int NOT NULL
);

CREATE TABLE categories (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255)
);

CREATE TABLE comments (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id INT,
	good_id INT,
	text VARCHAR(255),
	rating int NOT NULL,
	image_path VARCHAR(255),
	FOREIGN KEY(user_id) REFERENCES users(id),
	FOREIGN KEY(good_id) REFERENCES categories(id)
);

CREATE TABLE status (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255)
);

CREATE TABLE orders (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id INT,
	status_id INT,
	FOREIGN KEY(status_id) REFERENCES status(id)
);

INSERT INTO users(first_name, second_name, email, is_admin)
VALUES('Сергей', 'Птичкин', 'sergey.ptichkin@gmail.com', true);

INSERT INTO goods(name, cost, count)
VALUES('Айфон', 100000, 15);

INSERT INTO categories(name)
VALUES('Смартфоны');

CREATE TABLE good_category (
	good_id INT,
	category_id INT,
	FOREIGN KEY(good_id) REFERENCES goods(id),
	FOREIGN KEY(category_id) REFERENCES categories(id)
);

CREATE TABLE good_order (
	good_id INT,
	order_id INT,
	FOREIGN KEY(good_id) REFERENCES goods(id),
	FOREIGN KEY(order_id) REFERENCES orders(id)
);

INSERT INTO comments(user_id, good_id, text, rating)
VALUES(1, 1, 'Cool', 5);

INSERT INTO status(name)
VALUES('Оплачен');