DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS good_order;
DROP TABLE IF EXISTS good_category;
DROP TABLE IF EXISTS goods;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS status;

CREATE TABLE users (
	user_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255),
	second_name varchar(255),
	email varchar(255),
	password varchar(255),
	role varchar(10)
);

CREATE TABLE goods (
	good_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50),
	cost int NOT NULL,
	discount float,
	count int NOT NULL,
	manufacturer VARCHAR(50),
	description VARCHAR(255),
	image_path VARCHAR(255)
);

CREATE TABLE categories (
	category_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50),
	parent_id INT
);

CREATE TABLE comments (
	comment_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id INT,
	good_id INT,
	text VARCHAR(255),
	rating int NOT NULL,
	image_path VARCHAR(255),
	FOREIGN KEY(user_id) REFERENCES users(user_id),
	FOREIGN KEY(good_id) REFERENCES goods(good_id)
);

CREATE TABLE orders (
	order_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id INT
);

CREATE TABLE good_category (
	good_id INT NOT NULL,
	category_id INT NOT NULL,
	PRIMARY KEY (good_id, category_id),
	CONSTRAINT good_category_ibfk_1 FOREIGN KEY(good_id) REFERENCES goods(good_id),
	CONSTRAINT good_category_ibfk_2 FOREIGN KEY(category_id) REFERENCES categories(category_id)
);

CREATE TABLE good_order (
	good_id INT NOT NULL,
	order_id INT NOT NULL,
	PRIMARY KEY (good_id, order_id),
	FOREIGN KEY(good_id) REFERENCES goods(good_id),
	FOREIGN KEY(order_id) REFERENCES orders(order_id)
);

INSERT INTO users(first_name, second_name, email, password, role) VALUES
('Сергей', 'Птичкин', 'sergey.pti@gmail.com', 1234, 'ADMIN');

INSERT INTO goods(name, cost, discount, count, manufacturer, description, image_path) VALUES
('Смартфон iPhone 15', 86000, 0.0, 15, 'Apple', '128 ГБ черный [ядер - 6x(3.46 ГГц), 6 ГБ, 2 SIM, Super Retina XDR, 2556x1179, камера 48+12 Мп, NFC, 5G, GPS, 3349 мА*ч]', 'Смартфон Iphone 15.jpg'),
('Смартфон iPhone 15 PRO MAX', 214000, 0.05, 15, 'Apple', '1024 ГБ белый [ядер - 6x(3.78 ГГц), 8 ГБ, 2 SIM, Super Retina XDR, 2796x1290, камера 48+12+12 Мп, NFC, 5G, GPS, 4441 мА*ч]', 'Смартфон Iphone 15 PRO MAX.jpg'),
('Смартфон Samsung Galaxy A05', 12500, 0.0, 0, 'Samsung', '64 ГБ зеленый [ядер - 8x(2 ГГц), 4 ГБ, 2 SIM, PLS, 1600x720, камера 50+2 Мп, 4G, GPS, 5000 мА*ч]', 'Смартфон Sumsung A05.jpg'),
('Смартфон Samsung Galaxy A54 5G', 37000, 0.0, 17, 'Samsung', '256 ГБ черный [ядер - 8x(2.4 ГГц), 8 ГБ, 2 SIM, Super AMOLED, 2340x1080, камера 50+12+5 Мп, NFC, 5G, GPS, 5000 мА*ч]', 'Смартфон Samsung Galaxy A54 5G.jpg'),
('Смартфон Xiaomi Redmi Note 12', 16000, 0.0, 12, 'Xiaomi', '128 ГБ черный [ядер - 8x(2.8 ГГц), 6 ГБ, 2 SIM, AMOLED, 2400x1080, камера 50+8+2 Мп, NFC, 4G, GPS, FM, 5000 мА*ч]', 'Смартфон Xiaomi Redmi Note 12.jpg'),
('Смартфон Xiaomi 12X', 45000, 0.0, 5, 'Xiaomi', '128 ГБ голубой [ядер - 8x(3.2 ГГц), 8 ГБ, 2 SIM, AMOLED, 2400x1080, камера 50+13+5 Мп, NFC, 5G, GPS, 4500 мА*ч]', 'Смартфон Xiaomi 12X.jpg'),
('Планшет Apple iPad (6th Gen) Wi-Fi', 165000, 0.1, 30, 'Apple', '256 ГБ серый [2732x2048, IPS, 8x3.5 ГГц, 8 ГБ, 10702 мА*ч, iPadOS 16]', 'Планшет Apple iPad (9th Gen) Wi-Fi.jpg'),
('Планшет Apple iPad (10th Gen) Wi-Fi', 48000, 0.0, 11, 'Apple', '256 ГБ голубой [2360x16464 ГБ голубой [2360x1640, IPS, 6x3.1 ГГц, 4 ГБ, 7606 мА*ч, iPadOS 16]', 'Планшет Apple iPad (10th Gen) Wi-Fi.png'),
('Планшет Samsung Galaxy Tab A7 Lite LTE', 12000, 0.0, 20, 'Samsung', '64 ГБ серый [1340x800, PLS, 8x2.3 ГГц, 3 ГБ, 5100 мА*ч, Android 11.x]', 'Планшет Samsung Galaxy Tab A7 Lite LTE.jpg'),
('Планшет Samsung Galaxy Tab S9 FE Wi-Fi', 48000, 0.0, 0, 'Samsung', '256 ГБ серый + стилус [2304x1440, PLS, 8x2.4 ГГц, 8 ГБ, 8000 мА*ч, Android 13.x]', 'Планшет Samsung Galaxy Tab S9 FE Wi-Fi.jpg'),
('Планшет Xiaomi Redmi Pad Wi-Fi', 17000, 0.0, 13, 'Xiaomi', '64 ГБ серый [2000x1200, IPS, 8x2.2 ГГц, 3 ГБ, 8000 мА*ч, Android 12.x]', 'Планшет Xiaomi Redmi Pad Wi-Fi.jpg'),
('Планшет Xiaomi Pad 6 Wi-Fi', 37000, 0.0, 6, 'Xiaomi', '128 ГБ черный [2880x1800, IPS, 8x3.2 ГГц, 6 ГБ, 8840 мА*ч, Android 13.x]', 'Планшет Xiaomi Pad 6 Wi-Fi.jpg'),
('Компактный фотоаппарат Canon PowerShot SX70 HS', 74000, 0.0, 17, 'Canon', 'черный [20.3 Мп, фото: 5184x3888, видео 4K, зум 65 x, встроенная вспышка, дисплей 3", Bluetooth, GPS, Wi-Fi]', 'Canon SX70.jpg'),
('Компактный фотоаппарат Rekam iLook S990i', 8200, 0.0, 20, 'Rekam', 'серебристый [21 Мп, фото: 5616x3744, встроенная вспышка, дисплей 2.7"]', 'Rekam S990i.jpg'),
('Видеокамера Rekam ALLURE Zoom 1100', 22600, 0.0, 15, 'Rekam', '[4K, 2880х2160, матрица CMOS, дисплей 3", zoom 10 x]', 'Rekam Allure Zoom 1100.jpg'),
('Видеокамера Panasonic HC-VX980', 92000, 0.0, 0, 'Panasonic', '[4K, 3840x2160, матрица BSI MOS, 18.91 Мп, дисплей 3", zoom 20 x, Wi-Fi, 1940 мА*ч]', 'Видеокамера Panasonic HC-VX980.jpg'),
('LED-телевизор DEXP 24HKN1', 7900, 0.0, 18, 'DEXP', '24" (60 см) черный [Direct LED, HD, 60 Гц, HDMI х 2, USB х 2 шт]', 'Телевизор Dexp 24HKN1.jpg'),
('LED-телевизор DEXP 75UCY1/G', 60000, 0.0, 15, 'DEXP', '75" (190 см) серый [Direct LED, 4K UltraHD, Wi-Fi, 60 Гц, YaOS, HDMI х 3, USB х 2 шт]', 'Телевизор Dexp 75UCY1.jpg'),
('LED-телевизор Samsung UE50AU7002UXRU', 43000, 0.0, 43, 'Samsung', '50" (125 см) черный [Edge LED, 4K UltraHD, DLNA, Wi-Fi, 60 Гц, Tizen, HDMI х 3, USB х 1 шт]', 'Телевизор Samsung UE50AU.jpg'),
('LED-телевизор Samsung UE65CU7100UXRU', 70000, 0.0, 18, 'Samsung', '65" (163 см) черный [Edge LED, 4K UltraHD, DLNA, Wi-Fi, 60 Гц, Tizen, HDMI х 3, USB х 1 шт]', 'Телевизор Samsung UE65CU71.jpg'),
('LED-телевизор Philips 43PUS8108/60', 31500, 0.0, 15, 'Philips', '43" (108 см) черный [Direct LED, 4K UltraHD, DLNA, Wi-Fi, 60 Гц, фирменный интерфейс, HDMI х 3, USB х 2 шт]', 'Телевизор Philips 43PUS8108.jpg'),
('LED-телевизор Philips 65PUS8729/60', 80000, 0.0, 0, 'Philips', '65" (164 см) серый [Direct LED, 4K UltraHD, Wi-Fi, 120 Гц, Google TV, HDMI х 4, USB х 2 шт]', 'Телевизор Philips 65PUS8729.jpg'),
('Проводные наушники ARDOR GAMING Edge', 3800, 0.0, 10, 'ARDOR', 'черный [7.1 Virtual, охватывающие, 20 Гц - 20000 Гц, 32Ω, проводной, кабель - 1 м]', 'Наушники Ardor Gaming Edge.jpg'),
('Портативная колонка JBL Xtreme 3', 26800, 0.0, 56, 'JBL', 'черный [Bluetooth, AUX, 5000 мА*ч, время работы - до 15 ч]', 'JBL Xtreme 3.jpg'),
('Микрофон HyperX QuadCast S', 19000, 0.0, 60, 'HyperX', 'черный [проводной, настольный, -36 дБ, от 20 Гц до 20000 Гц, кабель - 300 см, jack 3.5 мм, USB]', 'HyperX QuadCast s.jpg'),
('ПК DEXP Atlas H422', 35500, 0.0, 78, 'DEXP', '[Intel Core i5-12400, 6 x 2.5 ГГц, 16 ГБ DDR4, SSD 512 ГБ, без ОС]', 'ПК DEXP Atlas H422.jpg'),
('ПК ARDOR GAMING RAGE H336', 143000, 0.0, 21, 'ARDOR', '[Intel Core i5-13400F, 6 x 2.5 ГГц, 32 ГБ DDR5, GeForce RTX 4070, SSD 1000 ГБ, без ОС]', 'ПК ARDOR GAMING RAGE H336.jpg'),
('Ноутбук MSI GF76 Katana B12UCX-1005XRU', 73000, 0.0, 75, 'MSI', '17.3" черный [Full HD (1920x1080), IPS, Intel Core i5-12450H, ядра: 4 + 4 х 2 ГГц + 1.5 ГГц, RAM 8 ГБ, SSD 256 ГБ, GeForce RTX 2050 4 ГБ, без ОС]', 'Ноутбук MSI GF76 KATANA.jpg'),
('Ноутбук ARDOR GAMING NEO G15-I5ND300', 77000, 0.0, 24, 'ARDOR', '15.6" черный [Full HD (1920x1080), IPS, Intel Core i5-12450H, ядра: 4 + 4 х 2 ГГц + 1.5 ГГц, RAM 16 ГБ, SSD 512 ГБ, GeForce RTX 3050 для ноутбуков 6 ГБ, без ОС]', 'Ноутбук ARDOR GAMING NEO G15-I5ND300.jpg'),
('Ноутбук ASUS Vivobook X1704ZA-AU123', 66000, 0.0, 3, 'ASUS', '17.3" синий [Full HD (1920x1080), IPS, Intel Core i5-1235U, ядра: 2 + 8 х 1.3 ГГц + 0.9 ГГц, RAM 16 ГБ, SSD 512 ГБ, Intel Iris Xe Graphics, без ОС]', 'Ноутбук ASUS Vivobook X1704ZA-AU123.jpg'),
('Ноутбук Apple MacBook Air', 120000, 0.0, 2, 'Apple', '13.6" черный [2560x1664, IPS, Apple M2, ядра: 4 + 4 х 3.5 ГГц + 2.4 ГГц, RAM 8 ГБ, SSD 256 ГБ, Apple M2 8-core, macOS]', 'Ноутбук Apple MacBook Air.jpg'),
('Ноутбук ASUS ROG Zephyrus G14 GA402XV-N2084W', 170000, 0.0, 0, 'ASUS', '14" серый [2560x1600, IPS, AMD Ryzen 9 7940HS, ядра: 8 х 4 ГГц, RAM 32 ГБ, SSD 1000 ГБ, GeForce RTX 4060 для ноутбуков 8 ГБ, Windows 11 Home Single Language]', 'Ноутбук ASUS ROG Zephyrus G14 GA402XV-N2084W.jpg'),
('Монитор MSI Optix G274QPX', 43000, 0.0, 8, 'MSI', '27" черный [2560x1440@240 Гц, IPS, LED, 1000:1, 400 Кд/м², 178°/178°, DisplayPort 1.4a, HDMI 2.0b x2, USB Type-C, NVIDIA G-SYNC Compatible]', 'Монитор MSI Optix G274QPX.jpg'),
('Монитор ARDOR GAMING LINK AF24H1UE', 14500, 0.0, 3, 'ARDOR', '23.8" черный [1920x1080 (FullHD)@180 Гц, IPS, LED, 1000:1, 350 Кд/м², 178°/178°, DisplayPort 1.4, HDMI 2.1 x2, USB х3 шт, AMD FreeSync Compatible, NVIDIA G-SYNC Compatible]', 'Монитор ARDOR GAMING LINK AF24H1UE.jpg'),
('Монитор Xiaomi Mi 2K Gaming Monitor', 32400, 0.0, 0, 'Xiaomi', '27" черный [2560x1440@165 Гц, IPS, LED, 1000:1, 400 Кд/м², 178°/178°, DisplayPort, HDMI x2, USB х2 шт, Adaptive-Sync]', 'Монитор Xiaomi Mi 2K Gaming Monitor.jpg'),
('Клавиатура ARDOR GAMING Blade', 4600, 0.0, 13, 'ARDOR', 'проводная [механическая Kailh Red, клавиш - 104, USB, черная]', 'Клавиатура проводная ARDOR GAMING Blade.jpg'),
('Клавиатура ARDOR GAMING Blade PRO', 4200, 0.0, 0, 'ARDOR', 'проводная [механическая Kailh Red, клавиш - 87, USB, черная]', 'Клавиатура проводная ARDOR GAMING Blade PRO.jpg'),
('Мышь ARDOR GAMING Fury', 1700, 0.0, 99, 'ARDOR', 'проводная черный [12400 dpi, светодиодный, USB Type-A, кнопки - 7]', 'Мышь проводная ARDOR GAMING Fury.jpg'),
('Мышь Logitech M90', 800, 0.0, 50, 'Logitech', 'проводная черный [1000 dpi, светодиодный, USB Type-A, кнопки - 3]', 'Мышь проводная Logitech M90 [910-001970].jpg'),
('Мышь ARDOR GAMING Phantom PRO V2', 4900, 0.0, 0, 'ARDOR', 'беспроводная черный [26000 dpi, светодиодный, USB Type-A, радиоканал, кнопки - 6]', 'Мышь ARDOR GAMING Phantom PRO V2.jpg');



INSERT INTO categories(name, parent_id) VALUES
('Смартфоны', NULL),
('Планшеты', NULL),
('Фототехника', NULL),
('Телевизоры', NULL),
('Аудиотехника', NULL),
('Компьютеры', NULL),
('Фотоаппараты', 3),
('Видеокамеры', 3),
('Наушники', 5),
('Портативные колонки', 5),
('Микрофоны', 5),
('ПК', 6),
('Ноутбуки', 6),
('Периферия', 6),
('Мониторы', 14),
('Клавиатуры', 14),
('Мыши', 14),
('Микрофоны', 14);
	

INSERT INTO comments(user_id, good_id, text, rating)
VALUES(1, 1, 'Cool', 5);

INSERT INTO good_category(good_id, category_id) VALUES
-- Смартфоны
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1),
(6, 1),
-- Планшеты
(7, 2),
(8, 2),
(9, 2),
(10, 2),
(11, 2),
(12, 2),
-- Фототехника
(13, 3),
(14, 3),
(15, 3),
(16, 3),
(13, 7),
(14, 7),
(15, 8),
(16, 8),
-- Телевизоры
(17, 4),
(18, 4),
(19, 4),
(20, 4),
(21, 4),
(22, 4),

-- Аудиотехника
(23, 5),
(24, 5),
(25, 5),
-- Наушники
(23, 9),
-- Портативные колонки
(24, 10),
-- Микрофоны
(25, 11),

-- Компьютеры
(25, 6),
(26, 6),
(27, 6),
(28, 6),
(29, 6),
(30, 6),
(31, 6),
(32, 6),
(33, 6),
(34, 6),
(35, 6),
(36, 6),
(37, 6),
(38, 6),
(39, 6),
(40, 6),
-- Компьютеры - ПК
(26, 12),
(27, 12),
-- Компьютеры - Ноутбуки
(28, 13),
(29, 13),
(30, 13),
(31, 13),
(32, 13),
-- Компьютеры - Периферия
(25, 14),
(33, 14),
(34, 14),
(35, 14),
(36, 14),
(37, 14),
(38, 14),
(39, 14),
(40, 14),

-- Компьютеры - Периферия - Мониторы
(33, 15),
(34, 15),
(35, 15),
-- Компьютеры - Периферия - Клавиатуры
(36, 16),
(37, 16),
-- Компьютеры - Периферия - Мыши
(38, 17),
(39, 17),
(40, 17),
-- Компьютеры - Периферия - Микрофоны
(25, 18);