DROP TABLE IF EXISTS order_details;
DROP TABLE IF EXISTS good_category;
DROP TABLE IF EXISTS goods;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(10)
);

CREATE TABLE users (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(50),
	second_name varchar(50),
	email varchar(255),
	password varchar(255),
	role_id INT NOT NULL,
	FOREIGN KEY(role_id) REFERENCES roles(id)
);

CREATE TABLE goods (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50),
	cost int NOT NULL,
	discount DECIMAL(10, 2),
	count int NOT NULL,
	manufacturer VARCHAR(50),
	description VARCHAR(255),
	image_path VARCHAR(255)
);

CREATE TABLE categories (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50),
	parent_id INT
);

CREATE TABLE orders (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id INT,
	date DATE
);

CREATE TABLE good_category (
	good_id INT NOT NULL,
	category_id INT NOT NULL,
	PRIMARY KEY (good_id, category_id),
	CONSTRAINT good_category_ibfk_1 FOREIGN KEY(good_id) REFERENCES goods(id),
	CONSTRAINT good_category_ibfk_2 FOREIGN KEY(category_id) REFERENCES categories(id)
);

CREATE TABLE order_details (
	good_id INT NOT NULL,
	order_id INT NOT NULL,
	quantity INT NOT NULL,
	PRIMARY KEY (good_id, order_id),
	FOREIGN KEY(good_id) REFERENCES goods(id),
	FOREIGN KEY(order_id) REFERENCES orders(id)
);